USE [master]
GO

/****** Object:  Database [SN]    Script Date: 08/24/2014 02:09:12 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'SN')
DROP DATABASE [SN]
GO

USE [master]
GO

/****** Object:  Database [SN]    Script Date: 08/24/2014 02:09:12 ******/
CREATE DATABASE [SN] ON  PRIMARY 
( NAME = N'SN', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SN.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SN_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\SN_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SN] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SN] SET ARITHABORT OFF 
GO

ALTER DATABASE [SN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SN] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SN] SET  READ_WRITE 
GO

ALTER DATABASE [SN] SET RECOVERY FULL 
GO

ALTER DATABASE [SN] SET  MULTI_USER 
GO

ALTER DATABASE [SN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SN] SET DB_CHAINING OFF 
GO

